<a href="https://colab.research.google.com/github/AbhishekShah272002/Machine-Learning-Study./blob/main/Learning-Labs/mushroom_secondary_data_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [75]:
df = pd.read_csv("mushroom secondary_data_csv.csv", delimiter=';')

In [76]:
df.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,...,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,...,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,...,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,...,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,...,s,y,w,u,w,t,p,NaN,d,w

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-surface           46949 non-null  object
 4   cap-color             61069 non-null  object
 5   does-bruise-or-bleed  61069 non-null  object
 6   gill-attachment       51185 non-null  object
 7   gill-spacing          36006 non-null  object
 8   gill-color            61069 non-null  object
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-root             9531 non-null   object
 12  stem-surface          22945 non-null  object
 13  stem-color            61069 non-null  object
 14  veil-type             3177 non-null   object
 15  veil-color            7413 non-null   object
 16  has-ring              61069 non-null  object
 17  ring-type             58598 non-null  object
 18  spore-print-color     6354 non-null   object
 19  habitat               61069 non-null  object
 20  season                61069 non-null  object
dtypes: float64(3), object(18)
memory usage: 9.8+ MB

In [78]:
missing_values = df.isnull().sum()
print(missing_values)

class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-root               51538
stem-surface            38124
stem-color                  0
veil-type               57892
veil-color              53656
has-ring                    0
ring-type                2471
spore-print-color       54715
habitat                     0
season                      0
dtype: int64

In [79]:
missing_values = df.isnull().sum()
missing_values_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_values_percentage
})

display(missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False))

                   Missing Count  Missing Percentage
veil-type                  57892           94.797688
spore-print-color          54715           89.595376
veil-color                 53656           87.861272
stem-root                  51538           84.393064
stem-surface               38124           62.427746
gill-spacing               25063           41.040462
cap-surface                14120           23.121387
gill-attachment             9884           16.184971
ring-type                   2471            4.046243

In [80]:

final_missing_check = df.isnull().sum()
final_missing_percentage = (df.isnull().sum() / len(df)) * 100

final_missing_df = pd.DataFrame({
    'Missing Count': final_missing_check,
    'Missing Percentage': final_missing_percentage
})

display(final_missing_df[final_missing_df['Missing Count'] > 90])

if final_missing_df['Missing Count'].sum() == 0:
    print("\nAll missing values have been successfully removed from the DataFrame.")
else:
    print("\nThere are still missing values in the DataFrame. Please review the output above.")

                   Missing Count  Missing Percentage
cap-surface                14120           23.121387
gill-attachment             9884           16.184971
gill-spacing               25063           41.040462
stem-root                  51538           84.393064
stem-surface               38124           62.427746
veil-type                  57892           94.797688
veil-color                 53656           87.861272
ring-type                   2471            4.046243
spore-print-color          54715           89.595376

There are still missing values in the DataFrame. Please review the output above.

In [82]:
missing_values = df.isnull().sum()
print(missing_values)

class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-root               51538
stem-surface            38124
stem-color                  0
veil-type               57892
veil-color              53656
has-ring                    0
ring-type                2471
spore-print-color       54715
habitat                     0
season                      0
dtype: int64

In [93]:
print('Original DataFrame info before encoding (cleaned):')
print(df.info())

categorical_cols = df.select_dtypes(include=['object']).columns
print(f"\nCategorical columns identified for encoding: {list(categorical_cols)}")

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print('\nDataFrame info after one-hot encoding:')
print(df_encoded.info())

print('\nFirst 5 rows of the encoded DataFrame:')
display(df_encoded.head())

Original DataFrame info before encoding (cleaned):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-color             61069 non-null  object
 4   does-bruise-or-bleed  61069 non-null  object
 5   gill-color            61069 non-null  object
 6   stem-height           61069 non-null  float64
 7   stem-width            61069 non-null  float64
 8   stem-color            61069 non-null  object
 9   has-ring              61069 non-null  object
 10  habitat               61069 non-null  object
 11  season                61069 non-null  object
dtypes: float64(3), object(9)
memory usage: 5.6+ MB
None

Categorical columns identified for encoding: ['class', 'cap-shape', 'cap-color', 'does-bruise-or-bleed', 'gill-color', 'stem-color', 'has-ring', 'habitat', 'season']

DataFrame info after one-hot encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 56 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   cap-diameter            61069 non-null  float64
 1   stem-height             61069 non-null  float64
 2   stem-width              61069 non-null  float64
 3   class_p                 61069 non-null  bool
 4   cap-shape_c             61069 non-null  bool
 5   cap-shape_f             61069 non-null  bool
 6   cap-shape_o             61069 non-null  bool
 7   cap-shape_p             61069 non-null  bool
 8   cap-shape_s             61069 non-null  bool
 9   cap-shape_x             61069 non-null  bool
 10  cap-color_e             61069 non-null  bool
 11  cap-color_g             61069 non-null  bool
 12  cap-color_k             61069 non-null  bool
 13  cap-color_l             61069 non-null  bool
 14  cap-color_n             61069 non-null  bool
 15  cap-color_o             61069 non-null  bool
 16  cap-color_p             61069 non-null  bool
 17  cap-color_r             61069 non-null  bool
 18  cap-color_u             61069 non-null  bool
 19  cap-color_w             61069 non-null  bool
 20  cap-color_y             61069 non-null  bool
 21  does-bruise-or-bleed_t  61069 non-null  bool
 22  gill-color_e            61069 non-null  bool
 23  gill-color_f            61069 non-null  bool
 24  gill-color_g            61069 non-null  bool
 25  gill-color_k            61069 non-null  bool
 26  gill-color_n            61069 non-null  bool
 27  gill-color_o            61069 non-null  bool
 28  gill-color_p            61069 non-null  bool
 29  gill-color_r            61069 non-null  bool
 30  gill-color_u            61069 non-null  bool
 31  gill-color_w            61069 non-null  bool
 32  gill-color_y            61069 non-null  bool
 33  stem-color_e            61069 non-null  bool
 34  stem-color_f            61069 non-null  bool
 35  stem-color_g            61069 non-null  bool
 36  stem-color_k            61069 non-null  bool
 37  stem-color_l            61069 non-null  bool
 38  stem-color_n            61069 non-null  bool
 39  stem-color_o            61069 non-null  bool
 40  stem-color_p            61069 non-null  bool
 41  stem-color_r            61069 non-null  bool
 42  stem-color_u            61069 non-null  bool
 43  stem-color_w            61069 non-null  bool
 44  stem-color_y            61069 non-null  bool
 45  has-ring_t              61069 non-null  bool
 46  habitat_g               61069 non-null  bool
 47  habitat_h               61069 non-null  bool
 48  habitat_l               61069 non-null  bool
 49  habitat_m               61069 non-null  bool
 50  habitat_p               61069 non-null  bool
 51  habitat_u               61069 non-null  bool
 52  habitat_w               61069 non-null  bool
 53  season_s                61069 non-null  bool
 54  season_u                61069 non-null  bool
 55  season_w                61069 non-null  bool
dtypes: bool(53), float64(3)
memory usage: 4.5 MB
None

First 5 rows of the encoded DataFrame:

,cap-diameter,stem-height,stem-width,class_p,cap-shape_c,cap-shape_f,cap-shape_o,cap-shape_p,cap-shape_s,cap-shape_x,...,habitat_g,habitat_h,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w,season_s,season_u,season_w
0,15.26,16.95,17.09,True,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
1,16.60,17.99,18.19,True,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
2,14.07,17.80,17.74,True,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
3,14.17,15.77,15.98,True,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,14.64,16.53,17.20,True,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True

In [96]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = encoder.fit_transform(df[col])

In [97]:
X = df.drop("class", axis=1)
y = df["class"]

In [98]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [99]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif

selector = SelectKBest(score_func=mutual_info_classif, k=10)

X_selected = selector.fit_transform(X_scaled, y)

selected_features = X.columns[selector.get_support()]

print(selected_features)

Index(['cap-diameter', 'cap-shape', 'cap-color', 'does-bruise-or-bleed',
       'gill-color', 'stem-height', 'stem-width', 'stem-color', 'habitat',
       'season'],
      dtype='object')

In [100]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_selected,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [101]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [102]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.9930407728835762
Precision: 0.9932203389830508
Recall   : 0.9942460902921215
F1 Score : 0.9937329499373295

Classification Report
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5436
           1       0.99      0.99      0.99      6778

    accuracy                           0.99     12214
   macro avg       0.99      0.99      0.99     12214
weighted avg       0.99      0.99      0.99     12214


Confusion Matrix
[[5390   46]
 [  39 6739]]